Replace legacy services with s6-rc definitions

diff --git a/s6-rc.d/caddy/run b/s6-rc.d/caddy/run
--- a/s6-rc.d/caddy/run
+++ b/s6-rc.d/caddy/run
@@ -1,7 +1,21 @@
-#!/command/execlineb -P
+#!/command/with-contenv sh
 # vi: ft=sh
+exec 2>&1
 
-with-contenv
+if [ -z "$CADDY_TARGET" ]; then
+  echo "ERROR: The environment variable CADDY_TARGET must be set"
+  exit 1
+fi
+
+if [ -z "$TS_HOSTNAME" ]; then
+  echo "ERROR: The environment variable TS_HOSTNAME must be set"
+  exit 1
+fi
+
+if [ -z "$TS_TAILNET" ]; then
+  echo "ERROR: The environment variable TS_TAILNET must be set"
+  exit 1
+fi
 
 cat > /etc/caddy/Caddyfile << CADDYFILE
 $TS_HOSTNAME.$TS_TAILNET.ts.net
@@ -22,4 +36,4 @@ forward_auth unix//run/tailscale.nginx-auth.sock {
 }
 CADDYFILE
 
-/usr/local/bin/caddy run --config=/etc/caddy/Caddyfile
+exec /usr/local/bin/caddy run --config=/etc/caddy/Caddyfile
